#
#
# The default compiler
CC = g++

# The CFLAGS variable sets compile flags for gcc:
#  -g          compile with debug information
#  -Wall       give verbose compiler warnings
#  -O0         do not optimize generated code
#  -std=c++11  use the c++ 11 specificeiont standard language definition
CFLAGS = -g -Wall -O0 -std=c++11 -Iinclude -I../json/json -I../json  -I../dv_json_rd_wr/include/


dv_json_unit_test: dv_json_unit_test.cpp ../dv_json_rd_wr/cjson_mngr.cpp ../json/jsoncpp.cpp
	$(CC) $(CFLAGS) -o dv_json_unit_test dv_json_unit_test.cpp ../dv_json_rd_wr/cjson_mngr.cpp ../json/jsoncpp.cpp 

.PHONY: clean

clean:
	rm -f *.o
